In [1]:
# 1. Create the following NumPy arrays:
# a) A 1-D array called zeros having 10 elements and all the elements are set to zero.
# b) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
# c) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
# d) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data:
#      2.7, -2, -19
#      0, 3.4, 99.9
#      10.6, 0, 13
# e) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.


# for first task 
import numpy as np 
zeros= np.zeros(10)
vowels = np.array(['a','e','i','o','u'])
ones = np.ones((2,5),dtype =int)
myarray1 = np.array([[2.7, -2, -19],[0, 3.4, 99.9],[10.6, 0, 13]])
myarray2 = np.arange(4,61,4).reshape(3,5)
myarray2



# 2. Using the arrays created in Exercise 1 above, write NumPy commands for the following:¶
# b) Reshape the array ones to have all the 10 elements in a single row.
# c) Display the 2nd and 3rd element of the array vowels.
# d) Display all elements in the 2nd and 3rd row of the array myarray1.
# e) Display the elements in the 1st and 2nd column of the array myarray1.
# f) Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
# g) Reverse the array of vowels


array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60]])

In [17]:
# a) Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros , vowels , ones , myarray1 and
# myarray2.
ndim = zeros.ndim, vowels.ndim, ones.ndim, myarray1.ndim, myarray2.ndim
shape = zeros.shape, vowels.shape, ones.shape, myarray1.shape, myarray2.shape
size = zeros.size, vowels.size, ones.size, myarray1.size, myarray2.size
dtype = zeros.dtype, vowels.dtype, ones.dtype, myarray1.dtype, myarray2.dtype
itemsize = zeros.itemsize, vowels.itemsize, ones.itemsize, myarray1.itemsize, myarray2.itemsize

# вывод 
ndim, dtype, size, shape, itemsize

((1, 1, 2, 2, 2),
 (dtype('float64'),
  dtype('<U1'),
  dtype('int64'),
  dtype('float64'),
  dtype('int64')),
 (10, 5, 10, 9, 15),
 ((10,), (5,), (2, 5), (3, 3), (3, 5)),
 (8, 4, 8, 8, 8))

In [80]:
# b) Reshape the array ones to have all the 10 elements in a single row.

# ones = 
# array([[1, 1, 1, 1, 1],
#        [1, 1, 1, 1, 1]])

ones.reshape(1, -1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
# c) Display the 2nd and 3rd element of the array vowels.
vowels[1:3]
# второй и третий элемент 

array(['e', 'i'], dtype='<U1')

In [23]:
# d) Display all elements in the 2nd and 3rd row of the array myarray1.
rows_two_and_three = myarray1[1:3, :]
rows_two_and_three


array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [29]:
# e) Display the elements in the 1st and 2nd column of the array myarray1.
column_one_and_two = myarray1[:, 0:2]
column_one_and_two 

array([[ 2.7, -2. ],
       [ 0. ,  3.4],
       [10.6,  0. ]])

In [50]:
# f) Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
myarray1[1:3, 0]

array([ 0. , 10.6])

In [81]:
# g) Reverse the array of vowels
np.flip(vowels)

# or this way 
vowels[ : : -1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')