In [2]:
import numpy as np

In [26]:
import numpy as np 
zeros= np.zeros(10)
vowels = np.array(['a','e','i','o','u'])
ones = np.ones((2,5),dtype =int)
myarray1 = np.array([[2.7, -2, -19],[0, 3.4, 99.9],[10.6, 0, 13]])
myarray2 = np.arange(4,61,4).reshape(3,5)
myarray2

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60]])

In [4]:
# a) Divide all elements of array ones by 3.
np.ones_like(myarray1) / 3

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [5]:
# b) Add the arrays myarray1 and myarray2.
# добавил к myarray1 столбцы, чтобы соответствовать форме myarray2
padded_myarray1 = np.pad(myarray1, ((0, 0), (0, 2)), 'constant'),

result = padded_myarray1 + myarray2
result

array([[[  6.7,   6. ,  -7. ,  16. ,  20. ],
        [ 24. ,  31.4, 131.9,  36. ,  40. ],
        [ 54.6,  48. ,  65. ,  56. ,  60. ]]])

In [28]:
# padded_myarray1 = np.pad(myarray1, ((0, 0), (0, 2)), 'constant')

# c) Subtract myarray1 from myarray2 and store the result in a new array.

# myarray1 = 
# array([[  2.7,  -2. , -19. ],
#        [  0. ,   3.4,  99.9],
#        [ 10.6,   0. ,  13. ]])

# myarray2 =
# array([[ 4,  8, 12, 16, 20],
#        [24, 28, 32, 36, 40],
#        [44, 48, 52, 56, 60]])

# 4 - 2.7 = 1.3 

subtracted_array = myarray2 - padded_myarray1
subtracted_array

array([[[  1.3,  10. ,  31. ,  16. ,  20. ],
        [ 24. ,  24.6, -67.9,  36. ,  40. ],
        [ 33.4,  48. ,  39. ,  56. ,  60. ]]])

In [7]:
# padded_myarray1 = np.pad(result2, ((0, 0), (0, 2)), 'constant')

#d) Multiply myarray1 and myarray2 elementwise.

result3 = padded_myarray1 * myarray2
result3

array([[[  10.8,  -16. , -228. ,    0. ,    0. ],
        [   0. ,   95.2, 3196.8,    0. ,    0. ],
        [ 466.4,    0. ,  676. ,    0. ,    0. ]]])

In [25]:
# e) Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
# first method 
myarray3 = np.dot(myarray1, myarray2)
myarray3

# second method
myarray1 @ myarray2

array([[ -873.2,  -946.4, -1019.6, -1092.8, -1166. ],
       [ 4477.2,  4890.4,  5303.6,  5716.8,  6130. ],
       [  614.4,   708.8,   803.2,   897.6,   992. ]])

In [9]:
# padded_myarray1 = np.pad(myarray1, ((0, 0), (0, 2)), 'constant')

# f) Divide myarray1 by myarray2.

padded_myarray1 / myarray2


array([[[ 0.675     , -0.25      , -1.58333333,  0.        ,
          0.        ],
        [ 0.        ,  0.12142857,  3.121875  ,  0.        ,
          0.        ],
        [ 0.24090909,  0.        ,  0.25      ,  0.        ,
          0.        ]]])

In [10]:
# g) Find the cube of all elements of myarray1 and divide the resulting array by 2.
myarray1 ** 3 / 2

array([[ 9.841500e+00, -4.000000e+00, -3.429500e+03],
       [ 0.000000e+00,  1.965200e+01,  4.985015e+05],
       [ 5.955080e+02,  0.000000e+00,  1.098500e+03]])

In [11]:
# h) Find the square root of all elements of myarray2 and divide the resulting array by 2. 
# The result should be rounded to two places of decimals.
np.around(myarray2 ** (1/2) / 2, 2)

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

In [13]:
myarray4 = np.arange(-1, -1 + 0.25 * (14 * 3), 0.25)
myarray4 = myarray4.reshape(14, 3)

split_arrays = np.array_split(myarray4, 3, axis = 0)
split_arrays

[array([[-1.  , -0.75, -0.5 ],
        [-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75],
        [ 2.  ,  2.25,  2.5 ]]),
 array([[2.75, 3.  , 3.25],
        [3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75],
        [5.  , 5.25, 5.5 ],
        [5.75, 6.  , 6.25]]),
 array([[6.5 , 6.75, 7.  ],
        [7.25, 7.5 , 7.75],
        [8.  , 8.25, 8.5 ],
        [8.75, 9.  , 9.25]])]

In [15]:
# a) Find the sum of all elements.
sum = np.sum(myarray4)
sum

173.25

In [18]:
# b) Find the sum of all elements row wise.
sum_rows = np.sum(myarray4, axis = 1)
sum_rows
# сумма элементов в каждой строке то есть 
# первая строка -1 -0.75 -0.5 = -2.25 и так далее

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])

In [19]:
# c) Find the sum of all elements column wise. Notes
sum_column = np.sum(myarray4, axis = 0) 
sum_column 

array([54.25, 57.75, 61.25])

In [20]:
# d) Find the max of all elements.
max_element = np.max(myarray4)
max_element

9.25

In [21]:
# e) Find the min of all elements in each row.
min_element = np.min(myarray4, axis = 1)
min_element

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ,  2.75,  3.5 ,  4.25,  5.  ,
        5.75,  6.5 ,  7.25,  8.  ,  8.75])

In [23]:
# f) Find the mean of all elements in each row.
average_mean = np.mean(myarray4, axis = 1)
average


array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ])

In [24]:
# g) Find the standard deviation column wise.
standard_deviation_column = np.std(myarray4, axis = 0)
standard_deviation_column

array([3.02334666, 3.02334666, 3.02334666])